# Generated by Django 5.2.5 on 2025-09-08 17:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('taxonomy', '0002_alter_skillgroup_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('book', 'Book'), ('certification', 'Certification'), ('practice', 'Practice'), ('documentation', 'Documentation'), ('workshop', 'Workshop'), ('video', 'Video'), ('article', 'Article'), ('tutorial', 'Tutorial')], default='course', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='not_started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usergoal')),
                ('related_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.skill')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'User Learning Resource',
                'verbose_name_plural': 'User Learning Resources',
                'ordering': ['-updated_at'],
                'unique_together': {('user_profile', 'title', 'url')},
            },
        ),
        migrations.CreateModel(
            name='UserResourceProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('session_duration_minutes', models.IntegerField(default=0)),
                ('progress_before', models.IntegerField(default=0)),
                ('progress_after', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_sessions', to='accounts.userlearningresource')),
            ],
            options={
                'verbose_name': 'Resource Progress Session',
                'verbose_name_plural': 'Resource Progress Sessions',
                'ordering': ['-session_date'],
            },
        ),
    ]
