# Generated by Django 5.2.5 on 2025-09-06 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0002_alter_skillgroup_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_name', models.CharField(help_text='Name of the career path', max_length=255)),
                ('description', models.TextField(help_text='Description of the career progression')),
                ('estimated_duration', models.CharField(help_text='Estimated time to progress through path', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to='taxonomy.occupation')),
            ],
            options={
                'db_table': 'ai_career_paths',
            },
        ),
        migrations.CreateModel(
            name='CareerStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_duration', models.CharField(help_text='Estimated time for this step', max_length=100)),
                ('requirements', models.TextField(help_text='Requirements to reach this step')),
                ('typical_salary_range', models.CharField(blank=True, help_text='Typical salary range for this level', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai_services.careerpath')),
            ],
            options={
                'db_table': 'ai_career_steps',
                'ordering': ['step_number'],
                'unique_together': {('career_path', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('course', 'Online Course'), ('book', 'Book'), ('tutorial', 'Tutorial'), ('certification', 'Certification'), ('bootcamp', 'Bootcamp'), ('workshop', 'Workshop'), ('documentation', 'Documentation'), ('practice', 'Practice Platform')], max_length=50)),
                ('url', models.URLField(blank=True, help_text='Link to the resource')),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('rating', models.FloatField(blank=True, help_text='Rating out of 5', null=True)),
                ('cost', models.CharField(blank=True, help_text='Cost information', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='taxonomy.skill')),
            ],
            options={
                'db_table': 'ai_learning_resources',
            },
        ),
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('growth_rate', models.FloatField(blank=True, help_text='Growth rate percentage', null=True)),
                ('remote_opportunities_percentage', models.FloatField(blank=True, help_text='Percentage of remote job opportunities', null=True)),
                ('demand_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20, null=True)),
                ('market_trends', models.TextField(blank=True, help_text='AI-generated market trends analysis')),
                ('key_regions', models.JSONField(default=list, help_text='List of key regions with demand')),
                ('industry_outlook', models.TextField(blank=True, help_text='Industry outlook analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_insight', to='taxonomy.occupation')),
            ],
            options={
                'db_table': 'ai_market_insights',
            },
        ),
        migrations.CreateModel(
            name='CareerStepSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importance_level', models.CharField(choices=[('essential', 'Essential'), ('important', 'Important'), ('helpful', 'Helpful'), ('optional', 'Optional')], default='important', max_length=20)),
                ('proficiency_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='ai_services.careerstep')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_steps', to='taxonomy.skill')),
            ],
            options={
                'db_table': 'ai_career_step_skills',
                'unique_together': {('career_step', 'skill')},
            },
        ),
    ]
