# Generated by Django 5.2.5 on 2025-09-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
    ]
